version: 0.0
os: linux
files:
  - source: /
    destination: /myproject/
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root 
      