version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - mvn test 
  post_build:
    commands:
      - mvn install
artifacts:
  files:
    - target/Spring_Boot_CICD_Deployment.jar